# DO NOT EDIT THIS FILE

.PHONY: test check

build:
	dune build

code:
	-dune build
	code .
	! dune build --watch

utop:
	OCAMLRUNPARAM=b dune utop lib

test:
	OCAMLRUNPARAM=b dune exec test/test.exe

game:
	OCAMLRUNPARAM=b dune exec bin/main.exe

zip:
	rm -f final_project.zip
	zip -r final_project.zip . 
clean:
	dune clean
	rm -f final_project.zip

doc:
	dune build @doc

opendoc: doc
	@bash opendoc.sh
